### ISSUE TITLE
Email page

### ISSUE THREAD

**Issue by AlexScorpion100** [kazemyavari/mazer-dark#1]
Hello, I'm reporting an issue that i don't if your already a were of, but on the email section it doesn't do the full dark mode, thank you!

![image](https://user-images.githubusercontent.com/36804913/161857040-c57420e0-9631-4771-949e-16d77b5abe3e.png)

**Comment by kazemyavari** [comment]
hi @AlexScorpion100
Thanks for reporting this issue.
Please check that these issue are now resolved.

 ![image](https://raw.githubusercontent.com/kazemyavari/mazer-dark/main/dist/assets/images/screen_email.PNG)

**Comment by AlexScorpion100** [comment]
beutifull, thank you so much
