### ISSUE TITLE
Accordeon component issue

### ISSUE THREAD

**Issue by mesayuda** [kazemyavari/mazer-dark#2]
hi an thanks for this template.

Could you please review the accordion component? the borders are not visible and it is not distinguished if it is an accordion or a simple text. thanks so much.

**Comment by kazemyavari** [comment]
hi
Thanks for reporting this issue.
Please check that these issue are now resolved.

**Comment by kazemyavari** [comment]
hi
Thanks for reporting this issue.
Please check that these issue are now resolved.

**Comment by kazemyavari** [comment]
hi @mesayuda 
Thanks for reporting this issue.
Please check that these issue are now resolved.

https://kazemyavari.freehost.io/mazer-dark/component-accordion.html
